name: CI Workflow

on:
  push:
    paths:
      - 'Dockerfile'
      - 'index.html'
      - 'java-app/**'
      - 'net-core-app/**'
  workflow_dispatch:

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ORGANIZATION: ${{ secrets.ORGANIZATION }}
      IMAGE_VERSION: latest  # Or you can set this dynamically based on your versioning strategy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update AWS CLI (if needed)
        run: |
          if aws --version; then
            echo "AWS CLI is already installed. Updating..."
          else
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker image - Dev
        run: |
          docker build . -t java-dotnet-apache:${{ env.IMAGE_VERSION }}

      - name: Tag Docker image - Dev
        run: |
          docker tag java-dotnet-apache:${{ env.IMAGE_VERSION }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-dev-repo:${{ env.IMAGE_VERSION }}
          docker tag java-dotnet-apache:${{ env.IMAGE_VERSION }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-dev-repo:${{ env.IMAGE_VERSION }}

      - name: Push Docker image to ECR - Dev
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-dev-repo:${{ env.IMAGE_VERSION }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-dev-repo:${{ env.IMAGE_VERSION }}

      - name: Build Docker image - Prod
        run: |
          docker build . -t java-dotnet-apache:${{ env.IMAGE_VERSION }}

      - name: Tag Docker image - Prod
        run: |
          docker tag java-dotnet-apache:${{ env.IMAGE_VERSION }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-prod-repo:${{ env.IMAGE_VERSION }}
          docker tag java-dotnet-apache:${{ env.IMAGE_VERSION }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-prod-repo:${{ env.IMAGE_VERSION }}

      - name: Push Docker image to ECR - Prod
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-prod-repo:${{ env.IMAGE_VERSION }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ORGANIZATION }}-prod-repo:${{ env.IMAGE_VERSION }}
